package com.zx.demo.domain.mybatis;

public class AuthorityResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_resource.authority_resource_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String authority_resource_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_resource.authority_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String authority_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_resource.resource_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String resource_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_resource.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_resource.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_resource.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_revisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_resource.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_revisor_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_resource.authority_resource_id
     *
     * @return the value of authority_resource.authority_resource_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getAuthority_resource_id() {
        return authority_resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority_resource.authority_resource_id
     *
     * @param authority_resource_id the value for authority_resource.authority_resource_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setAuthority_resource_id(String authority_resource_id) {
        this.authority_resource_id = authority_resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_resource.authority_id
     *
     * @return the value of authority_resource.authority_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getAuthority_id() {
        return authority_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority_resource.authority_id
     *
     * @param authority_id the value for authority_resource.authority_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setAuthority_id(String authority_id) {
        this.authority_id = authority_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_resource.resource_id
     *
     * @return the value of authority_resource.resource_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getResource_id() {
        return resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority_resource.resource_id
     *
     * @param resource_id the value for authority_resource.resource_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setResource_id(String resource_id) {
        this.resource_id = resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_resource.rec_creator
     *
     * @return the value of authority_resource.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_creator() {
        return rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority_resource.rec_creator
     *
     * @param rec_creator the value for authority_resource.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_creator(String rec_creator) {
        this.rec_creator = rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_resource.rec_create_time
     *
     * @return the value of authority_resource.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_create_time() {
        return rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority_resource.rec_create_time
     *
     * @param rec_create_time the value for authority_resource.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_create_time(String rec_create_time) {
        this.rec_create_time = rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_resource.rec_revisor
     *
     * @return the value of authority_resource.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_revisor() {
        return rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority_resource.rec_revisor
     *
     * @param rec_revisor the value for authority_resource.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_revisor(String rec_revisor) {
        this.rec_revisor = rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_resource.rec_revisor_time
     *
     * @return the value of authority_resource.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_revisor_time() {
        return rec_revisor_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority_resource.rec_revisor_time
     *
     * @param rec_revisor_time the value for authority_resource.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_revisor_time(String rec_revisor_time) {
        this.rec_revisor_time = rec_revisor_time;
    }
}