package com.zx.demo.domain.mybatis;

import java.util.ArrayList;
import java.util.List;

public class AuthorityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public AuthorityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAuthority_idIsNull() {
            addCriterion("authority_id is null");
            return (Criteria) this;
        }

        public Criteria andAuthority_idIsNotNull() {
            addCriterion("authority_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuthority_idEqualTo(String value) {
            addCriterion("authority_id =", value, "authority_id");
            return (Criteria) this;
        }

        public Criteria andAuthority_idNotEqualTo(String value) {
            addCriterion("authority_id <>", value, "authority_id");
            return (Criteria) this;
        }

        public Criteria andAuthority_idGreaterThan(String value) {
            addCriterion("authority_id >", value, "authority_id");
            return (Criteria) this;
        }

        public Criteria andAuthority_idGreaterThanOrEqualTo(String value) {
            addCriterion("authority_id >=", value, "authority_id");
            return (Criteria) this;
        }

        public Criteria andAuthority_idLessThan(String value) {
            addCriterion("authority_id <", value, "authority_id");
            return (Criteria) this;
        }

        public Criteria andAuthority_idLessThanOrEqualTo(String value) {
            addCriterion("authority_id <=", value, "authority_id");
            return (Criteria) this;
        }

        public Criteria andAuthority_idLike(String value) {
            addCriterion("authority_id like", value, "authority_id");
            return (Criteria) this;
        }

        public Criteria andAuthority_idNotLike(String value) {
            addCriterion("authority_id not like", value, "authority_id");
            return (Criteria) this;
        }

        public Criteria andAuthority_idIn(List<String> values) {
            addCriterion("authority_id in", values, "authority_id");
            return (Criteria) this;
        }

        public Criteria andAuthority_idNotIn(List<String> values) {
            addCriterion("authority_id not in", values, "authority_id");
            return (Criteria) this;
        }

        public Criteria andAuthority_idBetween(String value1, String value2) {
            addCriterion("authority_id between", value1, value2, "authority_id");
            return (Criteria) this;
        }

        public Criteria andAuthority_idNotBetween(String value1, String value2) {
            addCriterion("authority_id not between", value1, value2, "authority_id");
            return (Criteria) this;
        }

        public Criteria andAuthority_signIsNull() {
            addCriterion("authority_sign is null");
            return (Criteria) this;
        }

        public Criteria andAuthority_signIsNotNull() {
            addCriterion("authority_sign is not null");
            return (Criteria) this;
        }

        public Criteria andAuthority_signEqualTo(String value) {
            addCriterion("authority_sign =", value, "authority_sign");
            return (Criteria) this;
        }

        public Criteria andAuthority_signNotEqualTo(String value) {
            addCriterion("authority_sign <>", value, "authority_sign");
            return (Criteria) this;
        }

        public Criteria andAuthority_signGreaterThan(String value) {
            addCriterion("authority_sign >", value, "authority_sign");
            return (Criteria) this;
        }

        public Criteria andAuthority_signGreaterThanOrEqualTo(String value) {
            addCriterion("authority_sign >=", value, "authority_sign");
            return (Criteria) this;
        }

        public Criteria andAuthority_signLessThan(String value) {
            addCriterion("authority_sign <", value, "authority_sign");
            return (Criteria) this;
        }

        public Criteria andAuthority_signLessThanOrEqualTo(String value) {
            addCriterion("authority_sign <=", value, "authority_sign");
            return (Criteria) this;
        }

        public Criteria andAuthority_signLike(String value) {
            addCriterion("authority_sign like", value, "authority_sign");
            return (Criteria) this;
        }

        public Criteria andAuthority_signNotLike(String value) {
            addCriterion("authority_sign not like", value, "authority_sign");
            return (Criteria) this;
        }

        public Criteria andAuthority_signIn(List<String> values) {
            addCriterion("authority_sign in", values, "authority_sign");
            return (Criteria) this;
        }

        public Criteria andAuthority_signNotIn(List<String> values) {
            addCriterion("authority_sign not in", values, "authority_sign");
            return (Criteria) this;
        }

        public Criteria andAuthority_signBetween(String value1, String value2) {
            addCriterion("authority_sign between", value1, value2, "authority_sign");
            return (Criteria) this;
        }

        public Criteria andAuthority_signNotBetween(String value1, String value2) {
            addCriterion("authority_sign not between", value1, value2, "authority_sign");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameIsNull() {
            addCriterion("authority_name is null");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameIsNotNull() {
            addCriterion("authority_name is not null");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameEqualTo(String value) {
            addCriterion("authority_name =", value, "authority_name");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameNotEqualTo(String value) {
            addCriterion("authority_name <>", value, "authority_name");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameGreaterThan(String value) {
            addCriterion("authority_name >", value, "authority_name");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameGreaterThanOrEqualTo(String value) {
            addCriterion("authority_name >=", value, "authority_name");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameLessThan(String value) {
            addCriterion("authority_name <", value, "authority_name");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameLessThanOrEqualTo(String value) {
            addCriterion("authority_name <=", value, "authority_name");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameLike(String value) {
            addCriterion("authority_name like", value, "authority_name");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameNotLike(String value) {
            addCriterion("authority_name not like", value, "authority_name");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameIn(List<String> values) {
            addCriterion("authority_name in", values, "authority_name");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameNotIn(List<String> values) {
            addCriterion("authority_name not in", values, "authority_name");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameBetween(String value1, String value2) {
            addCriterion("authority_name between", value1, value2, "authority_name");
            return (Criteria) this;
        }

        public Criteria andAuthority_nameNotBetween(String value1, String value2) {
            addCriterion("authority_name not between", value1, value2, "authority_name");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionIsNull() {
            addCriterion("authority_description is null");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionIsNotNull() {
            addCriterion("authority_description is not null");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionEqualTo(String value) {
            addCriterion("authority_description =", value, "authority_description");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionNotEqualTo(String value) {
            addCriterion("authority_description <>", value, "authority_description");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionGreaterThan(String value) {
            addCriterion("authority_description >", value, "authority_description");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionGreaterThanOrEqualTo(String value) {
            addCriterion("authority_description >=", value, "authority_description");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionLessThan(String value) {
            addCriterion("authority_description <", value, "authority_description");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionLessThanOrEqualTo(String value) {
            addCriterion("authority_description <=", value, "authority_description");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionLike(String value) {
            addCriterion("authority_description like", value, "authority_description");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionNotLike(String value) {
            addCriterion("authority_description not like", value, "authority_description");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionIn(List<String> values) {
            addCriterion("authority_description in", values, "authority_description");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionNotIn(List<String> values) {
            addCriterion("authority_description not in", values, "authority_description");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionBetween(String value1, String value2) {
            addCriterion("authority_description between", value1, value2, "authority_description");
            return (Criteria) this;
        }

        public Criteria andAuthority_descriptionNotBetween(String value1, String value2) {
            addCriterion("authority_description not between", value1, value2, "authority_description");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindIsNull() {
            addCriterion("authority_remind is null");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindIsNotNull() {
            addCriterion("authority_remind is not null");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindEqualTo(String value) {
            addCriterion("authority_remind =", value, "authority_remind");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindNotEqualTo(String value) {
            addCriterion("authority_remind <>", value, "authority_remind");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindGreaterThan(String value) {
            addCriterion("authority_remind >", value, "authority_remind");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindGreaterThanOrEqualTo(String value) {
            addCriterion("authority_remind >=", value, "authority_remind");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindLessThan(String value) {
            addCriterion("authority_remind <", value, "authority_remind");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindLessThanOrEqualTo(String value) {
            addCriterion("authority_remind <=", value, "authority_remind");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindLike(String value) {
            addCriterion("authority_remind like", value, "authority_remind");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindNotLike(String value) {
            addCriterion("authority_remind not like", value, "authority_remind");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindIn(List<String> values) {
            addCriterion("authority_remind in", values, "authority_remind");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindNotIn(List<String> values) {
            addCriterion("authority_remind not in", values, "authority_remind");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindBetween(String value1, String value2) {
            addCriterion("authority_remind between", value1, value2, "authority_remind");
            return (Criteria) this;
        }

        public Criteria andAuthority_remindNotBetween(String value1, String value2) {
            addCriterion("authority_remind not between", value1, value2, "authority_remind");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNull() {
            addCriterion("isEnabled is null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNotNull() {
            addCriterion("isEnabled is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledEqualTo(String value) {
            addCriterion("isEnabled =", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotEqualTo(String value) {
            addCriterion("isEnabled <>", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThan(String value) {
            addCriterion("isEnabled >", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThanOrEqualTo(String value) {
            addCriterion("isEnabled >=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThan(String value) {
            addCriterion("isEnabled <", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThanOrEqualTo(String value) {
            addCriterion("isEnabled <=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLike(String value) {
            addCriterion("isEnabled like", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotLike(String value) {
            addCriterion("isEnabled not like", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIn(List<String> values) {
            addCriterion("isEnabled in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotIn(List<String> values) {
            addCriterion("isEnabled not in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledBetween(String value1, String value2) {
            addCriterion("isEnabled between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotBetween(String value1, String value2) {
            addCriterion("isEnabled not between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsSysIsNull() {
            addCriterion("isSys is null");
            return (Criteria) this;
        }

        public Criteria andIsSysIsNotNull() {
            addCriterion("isSys is not null");
            return (Criteria) this;
        }

        public Criteria andIsSysEqualTo(String value) {
            addCriterion("isSys =", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysNotEqualTo(String value) {
            addCriterion("isSys <>", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysGreaterThan(String value) {
            addCriterion("isSys >", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysGreaterThanOrEqualTo(String value) {
            addCriterion("isSys >=", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysLessThan(String value) {
            addCriterion("isSys <", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysLessThanOrEqualTo(String value) {
            addCriterion("isSys <=", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysLike(String value) {
            addCriterion("isSys like", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysNotLike(String value) {
            addCriterion("isSys not like", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysIn(List<String> values) {
            addCriterion("isSys in", values, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysNotIn(List<String> values) {
            addCriterion("isSys not in", values, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysBetween(String value1, String value2) {
            addCriterion("isSys between", value1, value2, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysNotBetween(String value1, String value2) {
            addCriterion("isSys not between", value1, value2, "isSys");
            return (Criteria) this;
        }

        public Criteria andRec_creatorIsNull() {
            addCriterion("rec_creator is null");
            return (Criteria) this;
        }

        public Criteria andRec_creatorIsNotNull() {
            addCriterion("rec_creator is not null");
            return (Criteria) this;
        }

        public Criteria andRec_creatorEqualTo(String value) {
            addCriterion("rec_creator =", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorNotEqualTo(String value) {
            addCriterion("rec_creator <>", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorGreaterThan(String value) {
            addCriterion("rec_creator >", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorGreaterThanOrEqualTo(String value) {
            addCriterion("rec_creator >=", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorLessThan(String value) {
            addCriterion("rec_creator <", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorLessThanOrEqualTo(String value) {
            addCriterion("rec_creator <=", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorLike(String value) {
            addCriterion("rec_creator like", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorNotLike(String value) {
            addCriterion("rec_creator not like", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorIn(List<String> values) {
            addCriterion("rec_creator in", values, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorNotIn(List<String> values) {
            addCriterion("rec_creator not in", values, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorBetween(String value1, String value2) {
            addCriterion("rec_creator between", value1, value2, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorNotBetween(String value1, String value2) {
            addCriterion("rec_creator not between", value1, value2, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeIsNull() {
            addCriterion("rec_create_time is null");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeIsNotNull() {
            addCriterion("rec_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeEqualTo(String value) {
            addCriterion("rec_create_time =", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeNotEqualTo(String value) {
            addCriterion("rec_create_time <>", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeGreaterThan(String value) {
            addCriterion("rec_create_time >", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeGreaterThanOrEqualTo(String value) {
            addCriterion("rec_create_time >=", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeLessThan(String value) {
            addCriterion("rec_create_time <", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeLessThanOrEqualTo(String value) {
            addCriterion("rec_create_time <=", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeLike(String value) {
            addCriterion("rec_create_time like", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeNotLike(String value) {
            addCriterion("rec_create_time not like", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeIn(List<String> values) {
            addCriterion("rec_create_time in", values, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeNotIn(List<String> values) {
            addCriterion("rec_create_time not in", values, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeBetween(String value1, String value2) {
            addCriterion("rec_create_time between", value1, value2, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeNotBetween(String value1, String value2) {
            addCriterion("rec_create_time not between", value1, value2, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisorIsNull() {
            addCriterion("rec_revisor is null");
            return (Criteria) this;
        }

        public Criteria andRec_revisorIsNotNull() {
            addCriterion("rec_revisor is not null");
            return (Criteria) this;
        }

        public Criteria andRec_revisorEqualTo(String value) {
            addCriterion("rec_revisor =", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorNotEqualTo(String value) {
            addCriterion("rec_revisor <>", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorGreaterThan(String value) {
            addCriterion("rec_revisor >", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorGreaterThanOrEqualTo(String value) {
            addCriterion("rec_revisor >=", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorLessThan(String value) {
            addCriterion("rec_revisor <", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorLessThanOrEqualTo(String value) {
            addCriterion("rec_revisor <=", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorLike(String value) {
            addCriterion("rec_revisor like", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorNotLike(String value) {
            addCriterion("rec_revisor not like", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorIn(List<String> values) {
            addCriterion("rec_revisor in", values, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorNotIn(List<String> values) {
            addCriterion("rec_revisor not in", values, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorBetween(String value1, String value2) {
            addCriterion("rec_revisor between", value1, value2, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorNotBetween(String value1, String value2) {
            addCriterion("rec_revisor not between", value1, value2, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeIsNull() {
            addCriterion("rec_revisor_time is null");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeIsNotNull() {
            addCriterion("rec_revisor_time is not null");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeEqualTo(String value) {
            addCriterion("rec_revisor_time =", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeNotEqualTo(String value) {
            addCriterion("rec_revisor_time <>", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeGreaterThan(String value) {
            addCriterion("rec_revisor_time >", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeGreaterThanOrEqualTo(String value) {
            addCriterion("rec_revisor_time >=", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeLessThan(String value) {
            addCriterion("rec_revisor_time <", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeLessThanOrEqualTo(String value) {
            addCriterion("rec_revisor_time <=", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeLike(String value) {
            addCriterion("rec_revisor_time like", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeNotLike(String value) {
            addCriterion("rec_revisor_time not like", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeIn(List<String> values) {
            addCriterion("rec_revisor_time in", values, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeNotIn(List<String> values) {
            addCriterion("rec_revisor_time not in", values, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeBetween(String value1, String value2) {
            addCriterion("rec_revisor_time between", value1, value2, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeNotBetween(String value1, String value2) {
            addCriterion("rec_revisor_time not between", value1, value2, "rec_revisor_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table authority
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 14 15:15:56 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}