package com.zx.demo.domain.mybatis;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String authority_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_sign
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String authority_sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_name
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String authority_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_description
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String authority_description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_remind
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String authority_remind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.isEnabled
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String isEnabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.isSys
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String isSys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_revisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_revisor_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_id
     *
     * @return the value of authority.authority_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getAuthority_id() {
        return authority_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_id
     *
     * @param authority_id the value for authority.authority_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setAuthority_id(String authority_id) {
        this.authority_id = authority_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_sign
     *
     * @return the value of authority.authority_sign
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getAuthority_sign() {
        return authority_sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_sign
     *
     * @param authority_sign the value for authority.authority_sign
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setAuthority_sign(String authority_sign) {
        this.authority_sign = authority_sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_name
     *
     * @return the value of authority.authority_name
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getAuthority_name() {
        return authority_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_name
     *
     * @param authority_name the value for authority.authority_name
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setAuthority_name(String authority_name) {
        this.authority_name = authority_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_description
     *
     * @return the value of authority.authority_description
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getAuthority_description() {
        return authority_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_description
     *
     * @param authority_description the value for authority.authority_description
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setAuthority_description(String authority_description) {
        this.authority_description = authority_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_remind
     *
     * @return the value of authority.authority_remind
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getAuthority_remind() {
        return authority_remind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_remind
     *
     * @param authority_remind the value for authority.authority_remind
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setAuthority_remind(String authority_remind) {
        this.authority_remind = authority_remind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.isEnabled
     *
     * @return the value of authority.isEnabled
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.isEnabled
     *
     * @param isEnabled the value for authority.isEnabled
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.isSys
     *
     * @return the value of authority.isSys
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.isSys
     *
     * @param isSys the value for authority.isSys
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setIsSys(String isSys) {
        this.isSys = isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.rec_creator
     *
     * @return the value of authority.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_creator() {
        return rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.rec_creator
     *
     * @param rec_creator the value for authority.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_creator(String rec_creator) {
        this.rec_creator = rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.rec_create_time
     *
     * @return the value of authority.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_create_time() {
        return rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.rec_create_time
     *
     * @param rec_create_time the value for authority.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_create_time(String rec_create_time) {
        this.rec_create_time = rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.rec_revisor
     *
     * @return the value of authority.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_revisor() {
        return rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.rec_revisor
     *
     * @param rec_revisor the value for authority.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_revisor(String rec_revisor) {
        this.rec_revisor = rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.rec_revisor_time
     *
     * @return the value of authority.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_revisor_time() {
        return rec_revisor_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.rec_revisor_time
     *
     * @param rec_revisor_time the value for authority.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_revisor_time(String rec_revisor_time) {
        this.rec_revisor_time = rec_revisor_time;
    }

    @Override
    public String toString() {
        return "Authority{" +
                "authority_id='" + authority_id + '\'' +
                ", authority_sign='" + authority_sign + '\'' +
                ", authority_name='" + authority_name + '\'' +
                ", authority_description='" + authority_description + '\'' +
                ", authority_remind='" + authority_remind + '\'' +
                ", isEnabled='" + isEnabled + '\'' +
                ", isSys='" + isSys + '\'' +
                ", rec_creator='" + rec_creator + '\'' +
                ", rec_create_time='" + rec_create_time + '\'' +
                ", rec_revisor='" + rec_revisor + '\'' +
                ", rec_revisor_time='" + rec_revisor_time + '\'' +
                '}';
    }
}