package com.zx.demo.domain.mybatis;

public class Resource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resource_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String resource_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resource_name
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String resource_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resource_type
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String resource_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resource_desc
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String resource_desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resource_path
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String resource_path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.isEnabled
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String isEnabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.isSys
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String isSys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_revisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_revisor_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resource_id
     *
     * @return the value of resource.resource_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getResource_id() {
        return resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resource_id
     *
     * @param resource_id the value for resource.resource_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setResource_id(String resource_id) {
        this.resource_id = resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resource_name
     *
     * @return the value of resource.resource_name
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getResource_name() {
        return resource_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resource_name
     *
     * @param resource_name the value for resource.resource_name
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setResource_name(String resource_name) {
        this.resource_name = resource_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resource_type
     *
     * @return the value of resource.resource_type
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getResource_type() {
        return resource_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resource_type
     *
     * @param resource_type the value for resource.resource_type
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setResource_type(String resource_type) {
        this.resource_type = resource_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resource_desc
     *
     * @return the value of resource.resource_desc
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getResource_desc() {
        return resource_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resource_desc
     *
     * @param resource_desc the value for resource.resource_desc
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setResource_desc(String resource_desc) {
        this.resource_desc = resource_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resource_path
     *
     * @return the value of resource.resource_path
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getResource_path() {
        return resource_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resource_path
     *
     * @param resource_path the value for resource.resource_path
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setResource_path(String resource_path) {
        this.resource_path = resource_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.isEnabled
     *
     * @return the value of resource.isEnabled
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.isEnabled
     *
     * @param isEnabled the value for resource.isEnabled
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.isSys
     *
     * @return the value of resource.isSys
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.isSys
     *
     * @param isSys the value for resource.isSys
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setIsSys(String isSys) {
        this.isSys = isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.rec_creator
     *
     * @return the value of resource.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_creator() {
        return rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.rec_creator
     *
     * @param rec_creator the value for resource.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_creator(String rec_creator) {
        this.rec_creator = rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.rec_create_time
     *
     * @return the value of resource.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_create_time() {
        return rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.rec_create_time
     *
     * @param rec_create_time the value for resource.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_create_time(String rec_create_time) {
        this.rec_create_time = rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.rec_revisor
     *
     * @return the value of resource.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_revisor() {
        return rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.rec_revisor
     *
     * @param rec_revisor the value for resource.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_revisor(String rec_revisor) {
        this.rec_revisor = rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.rec_revisor_time
     *
     * @return the value of resource.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_revisor_time() {
        return rec_revisor_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.rec_revisor_time
     *
     * @param rec_revisor_time the value for resource.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_revisor_time(String rec_revisor_time) {
        this.rec_revisor_time = rec_revisor_time;
    }

    @Override
    public String toString() {
        return "Resource{" +
                "resource_id='" + resource_id + '\'' +
                ", resource_name='" + resource_name + '\'' +
                ", resource_type='" + resource_type + '\'' +
                ", resource_desc='" + resource_desc + '\'' +
                ", resource_path='" + resource_path + '\'' +
                ", isEnabled='" + isEnabled + '\'' +
                ", isSys='" + isSys + '\'' +
                ", rec_creator='" + rec_creator + '\'' +
                ", rec_create_time='" + rec_create_time + '\'' +
                ", rec_revisor='" + rec_revisor + '\'' +
                ", rec_revisor_time='" + rec_revisor_time + '\'' +
                '}';
    }
}