package com.zx.demo.domain.mybatis;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String role_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String role_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_description
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String role_description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String role_authority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.isEnabled
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String isEnabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.isSys
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String isSys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_revisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_revisor_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_id
     *
     * @return the value of role.role_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_id
     *
     * @param role_id the value for role.role_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRole_id(String role_id) {
        this.role_id = role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRole_name() {
        return role_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param role_name the value for role.role_name
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRole_name(String role_name) {
        this.role_name = role_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_description
     *
     * @return the value of role.role_description
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRole_description() {
        return role_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_description
     *
     * @param role_description the value for role.role_description
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRole_description(String role_description) {
        this.role_description = role_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_authority
     *
     * @return the value of role.role_authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRole_authority() {
        return role_authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_authority
     *
     * @param role_authority the value for role.role_authority
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRole_authority(String role_authority) {
        this.role_authority = role_authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.isEnabled
     *
     * @return the value of role.isEnabled
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.isEnabled
     *
     * @param isEnabled the value for role.isEnabled
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.isSys
     *
     * @return the value of role.isSys
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.isSys
     *
     * @param isSys the value for role.isSys
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setIsSys(String isSys) {
        this.isSys = isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rec_creator
     *
     * @return the value of role.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_creator() {
        return rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rec_creator
     *
     * @param rec_creator the value for role.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_creator(String rec_creator) {
        this.rec_creator = rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rec_create_time
     *
     * @return the value of role.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_create_time() {
        return rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rec_create_time
     *
     * @param rec_create_time the value for role.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_create_time(String rec_create_time) {
        this.rec_create_time = rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rec_revisor
     *
     * @return the value of role.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_revisor() {
        return rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rec_revisor
     *
     * @param rec_revisor the value for role.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_revisor(String rec_revisor) {
        this.rec_revisor = rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rec_revisor_time
     *
     * @return the value of role.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_revisor_time() {
        return rec_revisor_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rec_revisor_time
     *
     * @param rec_revisor_time the value for role.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_revisor_time(String rec_revisor_time) {
        this.rec_revisor_time = rec_revisor_time;
    }

    @Override
    public String toString() {
        return "Role{" +
                "role_id='" + role_id + '\'' +
                ", role_name='" + role_name + '\'' +
                ", role_description='" + role_description + '\'' +
                ", role_authority='" + role_authority + '\'' +
                ", isEnabled='" + isEnabled + '\'' +
                ", isSys='" + isSys + '\'' +
                ", rec_creator='" + rec_creator + '\'' +
                ", rec_create_time='" + rec_create_time + '\'' +
                ", rec_revisor='" + rec_revisor + '\'' +
                ", rec_revisor_time='" + rec_revisor_time + '\'' +
                '}';
    }
}