package com.zx.demo.domain.mybatis;

import java.util.ArrayList;
import java.util.List;

public class RoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public RoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRole_idIsNull() {
            addCriterion("role_id is null");
            return (Criteria) this;
        }

        public Criteria andRole_idIsNotNull() {
            addCriterion("role_id is not null");
            return (Criteria) this;
        }

        public Criteria andRole_idEqualTo(String value) {
            addCriterion("role_id =", value, "role_id");
            return (Criteria) this;
        }

        public Criteria andRole_idNotEqualTo(String value) {
            addCriterion("role_id <>", value, "role_id");
            return (Criteria) this;
        }

        public Criteria andRole_idGreaterThan(String value) {
            addCriterion("role_id >", value, "role_id");
            return (Criteria) this;
        }

        public Criteria andRole_idGreaterThanOrEqualTo(String value) {
            addCriterion("role_id >=", value, "role_id");
            return (Criteria) this;
        }

        public Criteria andRole_idLessThan(String value) {
            addCriterion("role_id <", value, "role_id");
            return (Criteria) this;
        }

        public Criteria andRole_idLessThanOrEqualTo(String value) {
            addCriterion("role_id <=", value, "role_id");
            return (Criteria) this;
        }

        public Criteria andRole_idLike(String value) {
            addCriterion("role_id like", value, "role_id");
            return (Criteria) this;
        }

        public Criteria andRole_idNotLike(String value) {
            addCriterion("role_id not like", value, "role_id");
            return (Criteria) this;
        }

        public Criteria andRole_idIn(List<String> values) {
            addCriterion("role_id in", values, "role_id");
            return (Criteria) this;
        }

        public Criteria andRole_idNotIn(List<String> values) {
            addCriterion("role_id not in", values, "role_id");
            return (Criteria) this;
        }

        public Criteria andRole_idBetween(String value1, String value2) {
            addCriterion("role_id between", value1, value2, "role_id");
            return (Criteria) this;
        }

        public Criteria andRole_idNotBetween(String value1, String value2) {
            addCriterion("role_id not between", value1, value2, "role_id");
            return (Criteria) this;
        }

        public Criteria andRole_nameIsNull() {
            addCriterion("role_name is null");
            return (Criteria) this;
        }

        public Criteria andRole_nameIsNotNull() {
            addCriterion("role_name is not null");
            return (Criteria) this;
        }

        public Criteria andRole_nameEqualTo(String value) {
            addCriterion("role_name =", value, "role_name");
            return (Criteria) this;
        }

        public Criteria andRole_nameNotEqualTo(String value) {
            addCriterion("role_name <>", value, "role_name");
            return (Criteria) this;
        }

        public Criteria andRole_nameGreaterThan(String value) {
            addCriterion("role_name >", value, "role_name");
            return (Criteria) this;
        }

        public Criteria andRole_nameGreaterThanOrEqualTo(String value) {
            addCriterion("role_name >=", value, "role_name");
            return (Criteria) this;
        }

        public Criteria andRole_nameLessThan(String value) {
            addCriterion("role_name <", value, "role_name");
            return (Criteria) this;
        }

        public Criteria andRole_nameLessThanOrEqualTo(String value) {
            addCriterion("role_name <=", value, "role_name");
            return (Criteria) this;
        }

        public Criteria andRole_nameLike(String value) {
            addCriterion("role_name like", value, "role_name");
            return (Criteria) this;
        }

        public Criteria andRole_nameNotLike(String value) {
            addCriterion("role_name not like", value, "role_name");
            return (Criteria) this;
        }

        public Criteria andRole_nameIn(List<String> values) {
            addCriterion("role_name in", values, "role_name");
            return (Criteria) this;
        }

        public Criteria andRole_nameNotIn(List<String> values) {
            addCriterion("role_name not in", values, "role_name");
            return (Criteria) this;
        }

        public Criteria andRole_nameBetween(String value1, String value2) {
            addCriterion("role_name between", value1, value2, "role_name");
            return (Criteria) this;
        }

        public Criteria andRole_nameNotBetween(String value1, String value2) {
            addCriterion("role_name not between", value1, value2, "role_name");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionIsNull() {
            addCriterion("role_description is null");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionIsNotNull() {
            addCriterion("role_description is not null");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionEqualTo(String value) {
            addCriterion("role_description =", value, "role_description");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionNotEqualTo(String value) {
            addCriterion("role_description <>", value, "role_description");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionGreaterThan(String value) {
            addCriterion("role_description >", value, "role_description");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionGreaterThanOrEqualTo(String value) {
            addCriterion("role_description >=", value, "role_description");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionLessThan(String value) {
            addCriterion("role_description <", value, "role_description");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionLessThanOrEqualTo(String value) {
            addCriterion("role_description <=", value, "role_description");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionLike(String value) {
            addCriterion("role_description like", value, "role_description");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionNotLike(String value) {
            addCriterion("role_description not like", value, "role_description");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionIn(List<String> values) {
            addCriterion("role_description in", values, "role_description");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionNotIn(List<String> values) {
            addCriterion("role_description not in", values, "role_description");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionBetween(String value1, String value2) {
            addCriterion("role_description between", value1, value2, "role_description");
            return (Criteria) this;
        }

        public Criteria andRole_descriptionNotBetween(String value1, String value2) {
            addCriterion("role_description not between", value1, value2, "role_description");
            return (Criteria) this;
        }

        public Criteria andRole_authorityIsNull() {
            addCriterion("role_authority is null");
            return (Criteria) this;
        }

        public Criteria andRole_authorityIsNotNull() {
            addCriterion("role_authority is not null");
            return (Criteria) this;
        }

        public Criteria andRole_authorityEqualTo(String value) {
            addCriterion("role_authority =", value, "role_authority");
            return (Criteria) this;
        }

        public Criteria andRole_authorityNotEqualTo(String value) {
            addCriterion("role_authority <>", value, "role_authority");
            return (Criteria) this;
        }

        public Criteria andRole_authorityGreaterThan(String value) {
            addCriterion("role_authority >", value, "role_authority");
            return (Criteria) this;
        }

        public Criteria andRole_authorityGreaterThanOrEqualTo(String value) {
            addCriterion("role_authority >=", value, "role_authority");
            return (Criteria) this;
        }

        public Criteria andRole_authorityLessThan(String value) {
            addCriterion("role_authority <", value, "role_authority");
            return (Criteria) this;
        }

        public Criteria andRole_authorityLessThanOrEqualTo(String value) {
            addCriterion("role_authority <=", value, "role_authority");
            return (Criteria) this;
        }

        public Criteria andRole_authorityLike(String value) {
            addCriterion("role_authority like", value, "role_authority");
            return (Criteria) this;
        }

        public Criteria andRole_authorityNotLike(String value) {
            addCriterion("role_authority not like", value, "role_authority");
            return (Criteria) this;
        }

        public Criteria andRole_authorityIn(List<String> values) {
            addCriterion("role_authority in", values, "role_authority");
            return (Criteria) this;
        }

        public Criteria andRole_authorityNotIn(List<String> values) {
            addCriterion("role_authority not in", values, "role_authority");
            return (Criteria) this;
        }

        public Criteria andRole_authorityBetween(String value1, String value2) {
            addCriterion("role_authority between", value1, value2, "role_authority");
            return (Criteria) this;
        }

        public Criteria andRole_authorityNotBetween(String value1, String value2) {
            addCriterion("role_authority not between", value1, value2, "role_authority");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNull() {
            addCriterion("isEnabled is null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNotNull() {
            addCriterion("isEnabled is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledEqualTo(String value) {
            addCriterion("isEnabled =", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotEqualTo(String value) {
            addCriterion("isEnabled <>", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThan(String value) {
            addCriterion("isEnabled >", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThanOrEqualTo(String value) {
            addCriterion("isEnabled >=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThan(String value) {
            addCriterion("isEnabled <", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThanOrEqualTo(String value) {
            addCriterion("isEnabled <=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLike(String value) {
            addCriterion("isEnabled like", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotLike(String value) {
            addCriterion("isEnabled not like", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIn(List<String> values) {
            addCriterion("isEnabled in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotIn(List<String> values) {
            addCriterion("isEnabled not in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledBetween(String value1, String value2) {
            addCriterion("isEnabled between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotBetween(String value1, String value2) {
            addCriterion("isEnabled not between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsSysIsNull() {
            addCriterion("isSys is null");
            return (Criteria) this;
        }

        public Criteria andIsSysIsNotNull() {
            addCriterion("isSys is not null");
            return (Criteria) this;
        }

        public Criteria andIsSysEqualTo(String value) {
            addCriterion("isSys =", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysNotEqualTo(String value) {
            addCriterion("isSys <>", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysGreaterThan(String value) {
            addCriterion("isSys >", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysGreaterThanOrEqualTo(String value) {
            addCriterion("isSys >=", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysLessThan(String value) {
            addCriterion("isSys <", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysLessThanOrEqualTo(String value) {
            addCriterion("isSys <=", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysLike(String value) {
            addCriterion("isSys like", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysNotLike(String value) {
            addCriterion("isSys not like", value, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysIn(List<String> values) {
            addCriterion("isSys in", values, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysNotIn(List<String> values) {
            addCriterion("isSys not in", values, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysBetween(String value1, String value2) {
            addCriterion("isSys between", value1, value2, "isSys");
            return (Criteria) this;
        }

        public Criteria andIsSysNotBetween(String value1, String value2) {
            addCriterion("isSys not between", value1, value2, "isSys");
            return (Criteria) this;
        }

        public Criteria andRec_creatorIsNull() {
            addCriterion("rec_creator is null");
            return (Criteria) this;
        }

        public Criteria andRec_creatorIsNotNull() {
            addCriterion("rec_creator is not null");
            return (Criteria) this;
        }

        public Criteria andRec_creatorEqualTo(String value) {
            addCriterion("rec_creator =", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorNotEqualTo(String value) {
            addCriterion("rec_creator <>", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorGreaterThan(String value) {
            addCriterion("rec_creator >", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorGreaterThanOrEqualTo(String value) {
            addCriterion("rec_creator >=", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorLessThan(String value) {
            addCriterion("rec_creator <", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorLessThanOrEqualTo(String value) {
            addCriterion("rec_creator <=", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorLike(String value) {
            addCriterion("rec_creator like", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorNotLike(String value) {
            addCriterion("rec_creator not like", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorIn(List<String> values) {
            addCriterion("rec_creator in", values, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorNotIn(List<String> values) {
            addCriterion("rec_creator not in", values, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorBetween(String value1, String value2) {
            addCriterion("rec_creator between", value1, value2, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorNotBetween(String value1, String value2) {
            addCriterion("rec_creator not between", value1, value2, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeIsNull() {
            addCriterion("rec_create_time is null");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeIsNotNull() {
            addCriterion("rec_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeEqualTo(String value) {
            addCriterion("rec_create_time =", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeNotEqualTo(String value) {
            addCriterion("rec_create_time <>", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeGreaterThan(String value) {
            addCriterion("rec_create_time >", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeGreaterThanOrEqualTo(String value) {
            addCriterion("rec_create_time >=", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeLessThan(String value) {
            addCriterion("rec_create_time <", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeLessThanOrEqualTo(String value) {
            addCriterion("rec_create_time <=", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeLike(String value) {
            addCriterion("rec_create_time like", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeNotLike(String value) {
            addCriterion("rec_create_time not like", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeIn(List<String> values) {
            addCriterion("rec_create_time in", values, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeNotIn(List<String> values) {
            addCriterion("rec_create_time not in", values, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeBetween(String value1, String value2) {
            addCriterion("rec_create_time between", value1, value2, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeNotBetween(String value1, String value2) {
            addCriterion("rec_create_time not between", value1, value2, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisorIsNull() {
            addCriterion("rec_revisor is null");
            return (Criteria) this;
        }

        public Criteria andRec_revisorIsNotNull() {
            addCriterion("rec_revisor is not null");
            return (Criteria) this;
        }

        public Criteria andRec_revisorEqualTo(String value) {
            addCriterion("rec_revisor =", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorNotEqualTo(String value) {
            addCriterion("rec_revisor <>", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorGreaterThan(String value) {
            addCriterion("rec_revisor >", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorGreaterThanOrEqualTo(String value) {
            addCriterion("rec_revisor >=", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorLessThan(String value) {
            addCriterion("rec_revisor <", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorLessThanOrEqualTo(String value) {
            addCriterion("rec_revisor <=", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorLike(String value) {
            addCriterion("rec_revisor like", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorNotLike(String value) {
            addCriterion("rec_revisor not like", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorIn(List<String> values) {
            addCriterion("rec_revisor in", values, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorNotIn(List<String> values) {
            addCriterion("rec_revisor not in", values, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorBetween(String value1, String value2) {
            addCriterion("rec_revisor between", value1, value2, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorNotBetween(String value1, String value2) {
            addCriterion("rec_revisor not between", value1, value2, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeIsNull() {
            addCriterion("rec_revisor_time is null");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeIsNotNull() {
            addCriterion("rec_revisor_time is not null");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeEqualTo(String value) {
            addCriterion("rec_revisor_time =", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeNotEqualTo(String value) {
            addCriterion("rec_revisor_time <>", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeGreaterThan(String value) {
            addCriterion("rec_revisor_time >", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeGreaterThanOrEqualTo(String value) {
            addCriterion("rec_revisor_time >=", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeLessThan(String value) {
            addCriterion("rec_revisor_time <", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeLessThanOrEqualTo(String value) {
            addCriterion("rec_revisor_time <=", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeLike(String value) {
            addCriterion("rec_revisor_time like", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeNotLike(String value) {
            addCriterion("rec_revisor_time not like", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeIn(List<String> values) {
            addCriterion("rec_revisor_time in", values, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeNotIn(List<String> values) {
            addCriterion("rec_revisor_time not in", values, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeBetween(String value1, String value2) {
            addCriterion("rec_revisor_time between", value1, value2, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeNotBetween(String value1, String value2) {
            addCriterion("rec_revisor_time not between", value1, value2, "rec_revisor_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 14 15:15:56 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}