package com.zx.demo.domain.mybatis;

public class RoleAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority.role_authority_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String role_authority_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority.role_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String role_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority.rauthority_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rauthority_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_revisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_revisor_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority.role_authority_id
     *
     * @return the value of role_authority.role_authority_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRole_authority_id() {
        return role_authority_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority.role_authority_id
     *
     * @param role_authority_id the value for role_authority.role_authority_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRole_authority_id(String role_authority_id) {
        this.role_authority_id = role_authority_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority.role_id
     *
     * @return the value of role_authority.role_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority.role_id
     *
     * @param role_id the value for role_authority.role_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRole_id(String role_id) {
        this.role_id = role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority.rauthority_id
     *
     * @return the value of role_authority.rauthority_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRauthority_id() {
        return rauthority_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority.rauthority_id
     *
     * @param rauthority_id the value for role_authority.rauthority_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRauthority_id(String rauthority_id) {
        this.rauthority_id = rauthority_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority.rec_creator
     *
     * @return the value of role_authority.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_creator() {
        return rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority.rec_creator
     *
     * @param rec_creator the value for role_authority.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_creator(String rec_creator) {
        this.rec_creator = rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority.rec_create_time
     *
     * @return the value of role_authority.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_create_time() {
        return rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority.rec_create_time
     *
     * @param rec_create_time the value for role_authority.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_create_time(String rec_create_time) {
        this.rec_create_time = rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority.rec_revisor
     *
     * @return the value of role_authority.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_revisor() {
        return rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority.rec_revisor
     *
     * @param rec_revisor the value for role_authority.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_revisor(String rec_revisor) {
        this.rec_revisor = rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority.rec_revisor_time
     *
     * @return the value of role_authority.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_revisor_time() {
        return rec_revisor_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority.rec_revisor_time
     *
     * @param rec_revisor_time the value for role_authority.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_revisor_time(String rec_revisor_time) {
        this.rec_revisor_time = rec_revisor_time;
    }
}