package com.zx.demo.domain.mybatis;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(String value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(String value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(String value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(String value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLike(String value) {
            addCriterion("user_id like", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotLike(String value) {
            addCriterion("user_id not like", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<String> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<String> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(String value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(String value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(String value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(String value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(String value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(String value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLike(String value) {
            addCriterion("age like", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotLike(String value) {
            addCriterion("age not like", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<String> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<String> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(String value1, String value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(String value1, String value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andIsExpiredIsNull() {
            addCriterion("isExpired is null");
            return (Criteria) this;
        }

        public Criteria andIsExpiredIsNotNull() {
            addCriterion("isExpired is not null");
            return (Criteria) this;
        }

        public Criteria andIsExpiredEqualTo(String value) {
            addCriterion("isExpired =", value, "isExpired");
            return (Criteria) this;
        }

        public Criteria andIsExpiredNotEqualTo(String value) {
            addCriterion("isExpired <>", value, "isExpired");
            return (Criteria) this;
        }

        public Criteria andIsExpiredGreaterThan(String value) {
            addCriterion("isExpired >", value, "isExpired");
            return (Criteria) this;
        }

        public Criteria andIsExpiredGreaterThanOrEqualTo(String value) {
            addCriterion("isExpired >=", value, "isExpired");
            return (Criteria) this;
        }

        public Criteria andIsExpiredLessThan(String value) {
            addCriterion("isExpired <", value, "isExpired");
            return (Criteria) this;
        }

        public Criteria andIsExpiredLessThanOrEqualTo(String value) {
            addCriterion("isExpired <=", value, "isExpired");
            return (Criteria) this;
        }

        public Criteria andIsExpiredLike(String value) {
            addCriterion("isExpired like", value, "isExpired");
            return (Criteria) this;
        }

        public Criteria andIsExpiredNotLike(String value) {
            addCriterion("isExpired not like", value, "isExpired");
            return (Criteria) this;
        }

        public Criteria andIsExpiredIn(List<String> values) {
            addCriterion("isExpired in", values, "isExpired");
            return (Criteria) this;
        }

        public Criteria andIsExpiredNotIn(List<String> values) {
            addCriterion("isExpired not in", values, "isExpired");
            return (Criteria) this;
        }

        public Criteria andIsExpiredBetween(String value1, String value2) {
            addCriterion("isExpired between", value1, value2, "isExpired");
            return (Criteria) this;
        }

        public Criteria andIsExpiredNotBetween(String value1, String value2) {
            addCriterion("isExpired not between", value1, value2, "isExpired");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNull() {
            addCriterion("isEnabled is null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNotNull() {
            addCriterion("isEnabled is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledEqualTo(String value) {
            addCriterion("isEnabled =", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotEqualTo(String value) {
            addCriterion("isEnabled <>", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThan(String value) {
            addCriterion("isEnabled >", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThanOrEqualTo(String value) {
            addCriterion("isEnabled >=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThan(String value) {
            addCriterion("isEnabled <", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThanOrEqualTo(String value) {
            addCriterion("isEnabled <=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLike(String value) {
            addCriterion("isEnabled like", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotLike(String value) {
            addCriterion("isEnabled not like", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIn(List<String> values) {
            addCriterion("isEnabled in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotIn(List<String> values) {
            addCriterion("isEnabled not in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledBetween(String value1, String value2) {
            addCriterion("isEnabled between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotBetween(String value1, String value2) {
            addCriterion("isEnabled not between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsLockedIsNull() {
            addCriterion("isLocked is null");
            return (Criteria) this;
        }

        public Criteria andIsLockedIsNotNull() {
            addCriterion("isLocked is not null");
            return (Criteria) this;
        }

        public Criteria andIsLockedEqualTo(String value) {
            addCriterion("isLocked =", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedNotEqualTo(String value) {
            addCriterion("isLocked <>", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedGreaterThan(String value) {
            addCriterion("isLocked >", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedGreaterThanOrEqualTo(String value) {
            addCriterion("isLocked >=", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedLessThan(String value) {
            addCriterion("isLocked <", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedLessThanOrEqualTo(String value) {
            addCriterion("isLocked <=", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedLike(String value) {
            addCriterion("isLocked like", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedNotLike(String value) {
            addCriterion("isLocked not like", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedIn(List<String> values) {
            addCriterion("isLocked in", values, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedNotIn(List<String> values) {
            addCriterion("isLocked not in", values, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedBetween(String value1, String value2) {
            addCriterion("isLocked between", value1, value2, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedNotBetween(String value1, String value2) {
            addCriterion("isLocked not between", value1, value2, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredIsNull() {
            addCriterion("isCredentialsExpired is null");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredIsNotNull() {
            addCriterion("isCredentialsExpired is not null");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredEqualTo(String value) {
            addCriterion("isCredentialsExpired =", value, "isCredentialsExpired");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredNotEqualTo(String value) {
            addCriterion("isCredentialsExpired <>", value, "isCredentialsExpired");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredGreaterThan(String value) {
            addCriterion("isCredentialsExpired >", value, "isCredentialsExpired");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredGreaterThanOrEqualTo(String value) {
            addCriterion("isCredentialsExpired >=", value, "isCredentialsExpired");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredLessThan(String value) {
            addCriterion("isCredentialsExpired <", value, "isCredentialsExpired");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredLessThanOrEqualTo(String value) {
            addCriterion("isCredentialsExpired <=", value, "isCredentialsExpired");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredLike(String value) {
            addCriterion("isCredentialsExpired like", value, "isCredentialsExpired");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredNotLike(String value) {
            addCriterion("isCredentialsExpired not like", value, "isCredentialsExpired");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredIn(List<String> values) {
            addCriterion("isCredentialsExpired in", values, "isCredentialsExpired");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredNotIn(List<String> values) {
            addCriterion("isCredentialsExpired not in", values, "isCredentialsExpired");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredBetween(String value1, String value2) {
            addCriterion("isCredentialsExpired between", value1, value2, "isCredentialsExpired");
            return (Criteria) this;
        }

        public Criteria andIsCredentialsExpiredNotBetween(String value1, String value2) {
            addCriterion("isCredentialsExpired not between", value1, value2, "isCredentialsExpired");
            return (Criteria) this;
        }

        public Criteria andRec_creatorIsNull() {
            addCriterion("rec_creator is null");
            return (Criteria) this;
        }

        public Criteria andRec_creatorIsNotNull() {
            addCriterion("rec_creator is not null");
            return (Criteria) this;
        }

        public Criteria andRec_creatorEqualTo(String value) {
            addCriterion("rec_creator =", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorNotEqualTo(String value) {
            addCriterion("rec_creator <>", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorGreaterThan(String value) {
            addCriterion("rec_creator >", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorGreaterThanOrEqualTo(String value) {
            addCriterion("rec_creator >=", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorLessThan(String value) {
            addCriterion("rec_creator <", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorLessThanOrEqualTo(String value) {
            addCriterion("rec_creator <=", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorLike(String value) {
            addCriterion("rec_creator like", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorNotLike(String value) {
            addCriterion("rec_creator not like", value, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorIn(List<String> values) {
            addCriterion("rec_creator in", values, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorNotIn(List<String> values) {
            addCriterion("rec_creator not in", values, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorBetween(String value1, String value2) {
            addCriterion("rec_creator between", value1, value2, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_creatorNotBetween(String value1, String value2) {
            addCriterion("rec_creator not between", value1, value2, "rec_creator");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeIsNull() {
            addCriterion("rec_create_time is null");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeIsNotNull() {
            addCriterion("rec_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeEqualTo(String value) {
            addCriterion("rec_create_time =", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeNotEqualTo(String value) {
            addCriterion("rec_create_time <>", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeGreaterThan(String value) {
            addCriterion("rec_create_time >", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeGreaterThanOrEqualTo(String value) {
            addCriterion("rec_create_time >=", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeLessThan(String value) {
            addCriterion("rec_create_time <", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeLessThanOrEqualTo(String value) {
            addCriterion("rec_create_time <=", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeLike(String value) {
            addCriterion("rec_create_time like", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeNotLike(String value) {
            addCriterion("rec_create_time not like", value, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeIn(List<String> values) {
            addCriterion("rec_create_time in", values, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeNotIn(List<String> values) {
            addCriterion("rec_create_time not in", values, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeBetween(String value1, String value2) {
            addCriterion("rec_create_time between", value1, value2, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_create_timeNotBetween(String value1, String value2) {
            addCriterion("rec_create_time not between", value1, value2, "rec_create_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisorIsNull() {
            addCriterion("rec_revisor is null");
            return (Criteria) this;
        }

        public Criteria andRec_revisorIsNotNull() {
            addCriterion("rec_revisor is not null");
            return (Criteria) this;
        }

        public Criteria andRec_revisorEqualTo(String value) {
            addCriterion("rec_revisor =", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorNotEqualTo(String value) {
            addCriterion("rec_revisor <>", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorGreaterThan(String value) {
            addCriterion("rec_revisor >", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorGreaterThanOrEqualTo(String value) {
            addCriterion("rec_revisor >=", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorLessThan(String value) {
            addCriterion("rec_revisor <", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorLessThanOrEqualTo(String value) {
            addCriterion("rec_revisor <=", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorLike(String value) {
            addCriterion("rec_revisor like", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorNotLike(String value) {
            addCriterion("rec_revisor not like", value, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorIn(List<String> values) {
            addCriterion("rec_revisor in", values, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorNotIn(List<String> values) {
            addCriterion("rec_revisor not in", values, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorBetween(String value1, String value2) {
            addCriterion("rec_revisor between", value1, value2, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisorNotBetween(String value1, String value2) {
            addCriterion("rec_revisor not between", value1, value2, "rec_revisor");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeIsNull() {
            addCriterion("rec_revisor_time is null");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeIsNotNull() {
            addCriterion("rec_revisor_time is not null");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeEqualTo(String value) {
            addCriterion("rec_revisor_time =", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeNotEqualTo(String value) {
            addCriterion("rec_revisor_time <>", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeGreaterThan(String value) {
            addCriterion("rec_revisor_time >", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeGreaterThanOrEqualTo(String value) {
            addCriterion("rec_revisor_time >=", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeLessThan(String value) {
            addCriterion("rec_revisor_time <", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeLessThanOrEqualTo(String value) {
            addCriterion("rec_revisor_time <=", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeLike(String value) {
            addCriterion("rec_revisor_time like", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeNotLike(String value) {
            addCriterion("rec_revisor_time not like", value, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeIn(List<String> values) {
            addCriterion("rec_revisor_time in", values, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeNotIn(List<String> values) {
            addCriterion("rec_revisor_time not in", values, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeBetween(String value1, String value2) {
            addCriterion("rec_revisor_time between", value1, value2, "rec_revisor_time");
            return (Criteria) this;
        }

        public Criteria andRec_revisor_timeNotBetween(String value1, String value2) {
            addCriterion("rec_revisor_time not between", value1, value2, "rec_revisor_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 14 15:15:56 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}