package com.zx.demo.domain.mybatis;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.user_role_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String user_role_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.user_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.role_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String role_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_revisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    private String rec_revisor_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.user_role_id
     *
     * @return the value of user_role.user_role_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getUser_role_id() {
        return user_role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.user_role_id
     *
     * @param user_role_id the value for user_role.user_role_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setUser_role_id(String user_role_id) {
        this.user_role_id = user_role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.user_id
     *
     * @return the value of user_role.user_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.user_id
     *
     * @param user_id the value for user_role.user_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.role_id
     *
     * @return the value of user_role.role_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.role_id
     *
     * @param role_id the value for user_role.role_id
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRole_id(String role_id) {
        this.role_id = role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.rec_creator
     *
     * @return the value of user_role.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_creator() {
        return rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.rec_creator
     *
     * @param rec_creator the value for user_role.rec_creator
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_creator(String rec_creator) {
        this.rec_creator = rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.rec_create_time
     *
     * @return the value of user_role.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_create_time() {
        return rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.rec_create_time
     *
     * @param rec_create_time the value for user_role.rec_create_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_create_time(String rec_create_time) {
        this.rec_create_time = rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.rec_revisor
     *
     * @return the value of user_role.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_revisor() {
        return rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.rec_revisor
     *
     * @param rec_revisor the value for user_role.rec_revisor
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_revisor(String rec_revisor) {
        this.rec_revisor = rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.rec_revisor_time
     *
     * @return the value of user_role.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public String getRec_revisor_time() {
        return rec_revisor_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.rec_revisor_time
     *
     * @param rec_revisor_time the value for user_role.rec_revisor_time
     *
     * @mbg.generated Thu Dec 14 15:15:56 CST 2017
     */
    public void setRec_revisor_time(String rec_revisor_time) {
        this.rec_revisor_time = rec_revisor_time;
    }
}